spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 5678

# 自定义配置属性
com:
  yunqing:
    my-list:
      - 1
      - 2
      - 3
      - 4
    str: "我是配置的字符串"
    strPassword: 我是密码，需要双引号吗？显然不需要

#yunqing:
#  name: 111
#  email: 222