
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 80ad6bc7ae842be5bb2c
            clientSecret: 304407e313ddefb7c0fa62f0f792635c1f4914cd
server:
  port: 9090